# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'liChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks


pod ‘Firebase/Database’
pod ‘Firebase/Core’
pod ‘Firebase/Storage’
pod ‘Firebase/Firestore’ 
pod ‘Firebase/Auth’

pod ‘ProgressHUD’
pod ‘MBProgressHUD’
pod ‘IQAudioRecorderController’

pod ‘JSQMessagesViewController’, ‘7.3.3’
pod ‘IDMPhotoBrowser’
pod ‘RNCryptor’

pod 'OneSignal', '>= 2.6.2', '< 3.0'

pod ‘ImagePicker’



  # Pods for liChat

end



target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end